config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 resources :blog_posts
 resources :comments #, only: [:edit, :create, :update, :destroy]
 
 root 'blog_posts#index'

 get '/:name' => 'blog_posts#user_posts', as: :user_posts


# get '/:name' => 'blog_posts#user_posts', as: :user_posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user



	validates :title, :blog_entry, presence: true
	validates :title, uniqueness: true, length: {maximum: 140}

	paginates_per 3
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog_post
	belongs_to :user


	validates :comment, :blog_post_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
 
	has_many :blog_posts, dependent: :destroy
	has_many :comments, dependent: :destroy

validates :username, uniqueness: true

mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
   before_action :authenticate_user!
   
   protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys:[:username, :avatar])
  		devise_parameter_sanitizer.permit(:account_update, keys:[:username, :avatar])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  include ApplicationHelper

  def user_posts
    @user = User.find_by(username: params[:name])

  end

  def index
  	@blog_posts = BlogPost.all.page(params[:page])
  end

  def show
    @comment = Comment.new
  end

  def edit
    no_access_visitors(current_user, @blog_post)
  end

  def new
  	@blog_post = BlogPost.new
  end

  def create
  	@blog_post = BlogPost.new(blog_post_params)
  	 respond_to do |format|
  		  if @blog_post.save
  			   # format.html {redirect_to @blog_post.url (@blog_post), notice: "Blog Post was successfullyy created"}
  		     format.html {redirect_to root_path }

        else
  			   format.html {render :new }
        end
     end
  end

	def update
		  respond_to do |format|
		    if @blog_post.update(blog_post_params)
			       format.html { redirect_to blog_post_url(@blog_post), notice: "Blog was successfully update!"}
		    else
			     format.html {render :edit}
	      end
      end 
  end


      def destroy
	       @blog_post.destroy
	         respond_to do |format|
	           format.html { redirect_to blog_post_url, notice: "Your Blog Post was destroyeddd!!!"}
           end
      end

  private

    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end
    
    def blog_post_params
      params.require(:blog_post).permit(:title, :blog_entry, :user_id)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_comment, only: [:edit, :update, :destroy]
	
include ApplicationHelper

  def edit
    @blog_post = BlogPost.find(@comment.blog_post_id)
    no_access_visitors(current_user, @blog_post)
  end

  def create
  	@comment = Comment.new(comment_params)

  	respond_to do |format|
  		if @comment.save
  			format.html {redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Comment was created successfully!"}
  		else
  			format.html {redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Comment failed to post!"}
  		end
  	end
  end



  def update
  	respond_to do |format|
  		if @comment.update(comment_params)
  			format.html {redirect_to blog_post_url(id: @comment.blog_post_id), 
  				notice: "Comment was successfully updated"}
  		else
  			format.html { render :edit} 
  		end
  	end
  end
  def destroy
  	@comment.destroy
  	respond_to do |format|
  		format.html {redirect_to blog_post_url(id: @comment.blog_post_id),
  		 notice: "Your comment was deleted."}
  	end
  end
  private 
  def comment_params
  	params.require(:comment).permit(:comment, :user_id, :blog_post_id)
end
def set_comment
	@comment = Comment.find(params[:id])
end
end

#on this page line 45 added the word body to it to allow
#following should be posts/show
# <% content_for(:title, @post.title ) %>
# <p id="notice"><%= notice %></p>

# <h1>Blog</h1>
# <br>
# <div>
#   <%= image_tag @post.image.full.url %>
# </div>
# <div class="panel panel-default">
#   <div class="panel-heading">
#     <h2><em><%= @post.title %></em></h2>
#   </div>
#   <div class="panel-body">
#     <p><%= @post.content %></p>
#   </div>
# </div>

# <%= link_to 'Edit', edit_post_path(@post) %> |
# <%= link_to 'Back', posts_path %>

# <% @post.comments.each do |comment| %>
#   <%= comment.body %>
# <% end %>

# <%= form_for [@post, @post.comments.build] do |f| %>
#   <%= f.text_area :body %>
#   <%= f.submit "Submit" %>
# <% end %>
# <p>Comments: <%= @post.comments.count %></p>



#posts model like this
# class Post < ActiveRecord::Base
#     has_many :comments, dependent: :destroy
#     mount_uploader :image, PostUploader 

# end


#comments model

# class Comment < ActiveRecord::Base
#     belongs_to :user
#     belongs_to :post
# end

# #schema file
# create_table "comments", force: :cascade do |t|
#     t.string   "body"
#     t.integer  "user_id"
#     t.integer  "employee_id"
#     t.datetime "created_at",  null: false
#     t.datetime "updated_at",  null: false
#     t.integer  "post_id"
#   end

#   add_index "comments", ["employee_id"], name: "index_comments_on_employee_id"
#   add_index "comments", ["post_id"], name: "index_comments_on_post_id"
#   add_index "comments", ["user_id"], name: "index_comments_on_user_id"

#   create_table "posts", force: :cascade do |t|
#     t.string   "title"
#     t.text     "content"
#     t.datetime "created_at", null: false
#     t.datetime "updated_at", null: false
#     t.string   "image"
#   end

#   create_table "users", force: :cascade do |t|
#     t.string   "first_name"
#     t.string   "last_name"
#     t.string   "username"
#     t.datetime "created_at",                          null: false
#     t.datetime "updated_at",                          null: false
#     t.string   "email",                  default: "", null: false
#     t.string   "encrypted_password",     default: "", null: false
#     t.string   "reset_password_token"
#     t.datetime "reset_password_sent_at"
#     t.datetime "remember_created_at"
#     t.integer  "sign_in_count",          default: 0,  null: false
#     t.datetime "current_sign_in_at"
#     t.datetime "last_sign_in_at"
#     t.string   "current_sign_in_ip"
#     t.string   "last_sign_in_ip"
#   end

#   add_index "users", ["email"], name: "index_users_on_email", unique: true
#   add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true

app/helpers/application_helper.rb
module ApplicationHelper

def no_access_visitors(current_user, post_user)
	unless current_user.id == post_user.user.id
		redirect_to root_url
end
end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |form| %>

   

	<div class="form-group">
	<%= form.text_field :title, class: "form-control", placeholder: "Your Title Goes Here" %>
		</div>
	<div class="form-group hidden">
	<%= form.number_field :user_id, value: current_user.id %>
		</div>
	<div class="form-group">
	<%= form.text_area :blog_entry, class: "form-control",rows: 12, placeholder: "Tell us something." %>
		</div>


	<div class="form-group hidden">
		<strong>Uploaded Proflile Pic:</strong>
		<%= form.file_field :avatar, value: current_user.avatar %>
	</div>

	<div class="actions">
		<%= form.submit "Submit", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>
<%= image_tag current_user.avatar.url %>
<!-- or -->
<%= image_tag @blog_post.user.avatar.url %>
 <!-- need to choose one -->

<%= render 'form' %>

<br>

<%= link_to "Back", blog_post_path(@blog_post), class: "btn btn-info" %>
<%= link_to "All Blog Posts", blog_post_path, class: "btn btn-default" %>

app/views/blog_posts/index.html.erb
<h1> Welcome <%= current_user.username %></h1>


<h1>Current Blog Post</h1>


<div class="row">
	<% @blog_posts.each do |blog_post| %>
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<%= link_to blog_post.title, blog_post_path(id: blog_post.id) %>
			</div>
			<div class="panel-body">
			 by <em><%=link_to blog_post.user.username, blog_post_url(id: blog_post.user.username) %></em><br>
			  <p><%= time_ago_in_words(blog_post.created_at) %> ago</p>
			   <p> <%= blog_post.blog_entry[0...150].html_safe %> .. <%= link_to "Read more", blog_post %></p>
			</div>
			<% if current_user.id == blog_post.user_id %>
			<div class="panel-footer">
			
				<%= link_to "Edit", edit_blog_post_path(blog_post), class: "btn btn-warning" %>
				<%= link_to "Destroy", blog_post_path(blog_post), method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-danger" %>
		     </div>
		     <% end %>
		  </div>
	   </div>
	<% end %>
</div>

<%= paginate @blog_posts %>

app/views/blog_posts/new.html.erb
<h1>Create New Blog Post</h1>

<%= render 'form' %>
<br>

<%= link_to "All BLog Posts", root_path, class: "btn btn-default" %>

app/views/blog_posts/show.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<%= @blog_post.title %>
	</div>
	<div class="panel-body">
		<p> by <%= @blog_post.user.username %></p>
		<p><%= time_ago_in_words(@blog_post.created_at) %> ago </p>
		<p><%= @blog_post.blog_entry.html_safe %></p>
	</div>
	<% if current_user.id == @blog_post.user_id %>
	<div class="panel-footer">
		<%= link_to "Edit", edit_blog_post_path(@blog_post), class: "btn btn-warning" %>
	<% end %>
		<%= link_to "All Posts", blog_posts_path, class: "btn btn-default" %>
	</div>
   </div>
<div class="panel panel-success">
	<div class= "panel-heading">
		make a comment.....
	</div>
	<div class="panel-body">
		<%= render 'comments/form' %>
	</div>
</div>
<div class="panel panel-success">
	<div class="panel-heading">
		All comments.....
	</div>
		<div class="panel-body">
			<%= render @comment %>
		</div>
</div>

app/views/blog_posts/user_posts.html.erb
<h1> All Posts By <%= user.username %></h1>

<% @user.blog_posts.each do |blog_post| %>
	<div class="row">
		<div class="col-md-12">
			<div class="well">
				<h3><%= link_to blog_post.title, blog_post %></h3>
				<p><em> posted on <%= blog_post.created_at.strftime("%m/%d/%y at %l:%M%P") %></em></p>
				<p><%= blog_posts.blog_entry.html_safe %></p>
				<p>
					<%= link_to 'Show', blog_post, class "btn btn-info" %>
					<% if current_user.id == blog_post.user_id %>

					<p><%= link_to 'Edit', edit_blog_post_path(blog_post), class "btn btn-warning" %>
					<%= link_to 'Destroy', blog_post, method: :delete, data: {confirm: 'Are you sure?' }, class "btn btn-danger"%>
				</p>
			  <% end %>
			</div>
		</div>
	</div>


	<% end %>

app/views/comments/_comment.html.erb
<% @blog_post.comments.each do |comment| %>

<h4> 
	<%= link_to comment.user.username, user_posts_path(id: comment.user.username) %>
</h4>
<p>
	<%= time_ago_in_words(comment.created_at) %> ago
</p>

<p>
	<%= comment.comment %>
</p>

<% if current_user.id == comment.user_id %>
  <%= link_to "Edit", edit_comment_path(comment), class: "btn btn-warning" %>
  <%= link_to "Delete", comment_path(comment), method: :delete, data: {confirm: "Are You Sure?" }, class: "btn btn-danger" %>
  <% end %>

<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |form| %>
<%= @comment.errors.any? %>
<div class= 'error_explanation'>
	<h2><%= pluralize(@comment.errors.count, "error") %>
	prohibited this comment from being saved: </h2>
	<ul>   <% @comment.errors.full_messages.each do |message| %>
		<li> <%= message %> </li>
	  </ul>
	</div>
<% end %>

<div class='form-group hidden'>
	<% form.number_field :user_id, value: current_user.id %>
	</div>

<div class="form-group">
	<%= form.text_area :comment, rows: 4, class: "form-control", placeholder: "Your comment goes here." %>
</div>

		<div class="form-group hidden">
	<%= form.number_field :blog_post_id, value: @blog_post.id %>
		</div>



<div class="actions">
	<%= form.submit "Set Comment", class: "btn btn-default"%>
		</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

<br>


<%= link_to "Back", blog_post_path9@comment.blog_post_id), class: "btn btn-info" %>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "All_Blog_posts", root_path, class: "navabr-brand" %></li>
        <li><%= link_to  "New Blog Post", new_blog_post_path %></li>
      </ul>
      </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 

              <% if current_user.avatar.url != nil %>


            <%= image_tag current_user.avatar.url, class: "nav-image" %>
             <% end %>
            <%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">

        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
       <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
  <%= render 'layouts/navbar' %>
<div class="container">
    <%= yield %>
  </div>
  </body>
</html>